version: 2

global_defaults: &global_defaults
  working_directory: ~/forty-time-management

ruby_defaults: &ruby_defaults
  <<: *global_defaults
  docker:
    - image: ruby:2.6.5

typescript_defaults: &typescript_defaults
  <<: *global_defaults
  docker:
    - image: node:10.15.3

jobs:
  build_ruby:
    <<: *ruby_defaults
    steps:
      - checkout

      - run:
          name: Gem install bundler
          command: gem update --system && gem install bundler

      - restore_cache:
          name: Restore bundler cache
          key: bundler-{{ checksum "ruby/Gemfile.lock" }}

      - run:
          name: Bundle install
          command: cd ruby && bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          name: Save bundler cache
          key: bundler-{{ checksum "ruby/Gemfile.lock" }}
          paths:
            - ruby/vendor/bundle

  test_ruby:
    <<: *ruby_defaults
    steps:
      - checkout

      - run:
          name: Gem install bundler
          command: gem update --system && gem install bundler

      - restore_cache:
          name: Restore bundler cache
          key: bundler-{{ checksum "ruby/Gemfile.lock" }}

      - run:
          name: Bundle install
          command: cd ruby && bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Run tests
          command: cd ruby && bundle exec rake

  deploy_ruby:
    <<: *ruby_defaults
    steps:
      - checkout

      - run:
          name: Setup Rubygems
          command: bash .circleci/setup-rubygems

      - run:
          name: Build gem
          command: cd ruby && gem build forty_time.gemspec --output forty_time.gem

      - run:
          name: Publish gem
          command: cd ruby && gem push forty_time.gem

  build_typescript:
    <<: *typescript_defaults
    steps:
      - checkout

      - restore_cache:
          name: Restore yarn cache
          key: yarn-{{ checksum "typescript/yarn.lock" }}

      - run:
          name: Yarn install
          command: cd typescript && yarn install

      - save_cache:
          name: Save yarn cache
          key: yarn-{{ checksum "typescript/yarn.lock" }}
          paths:
            - typescript/node_modules/

  test_typescript:
    <<: *typescript_defaults
    steps:
      - checkout

      - restore_cache:
          name: Restore yarn cache
          key: yarn-{{ checksum "typescript/yarn.lock" }}

      - run:
          name: Yarn install
          command: cd typescript && yarn install

      - run:
          name: Run tests
          command: cd typescript && yarn prettier-check && yarn lint && yarn type-check && yarn test

  deploy_typescript:
    <<: *typescript_defaults
    steps:
      - checkout

      - run:
          name: Setup NPM
          command: bash .circleci/setup-npm

      - restore_cache:
          name: Restore yarn cache
          key: yarn-{{ checksum "typescript/yarn.lock" }}

      - run:
          name: Yarn install
          command: cd typescript && yarn install

      - run:
          name: Build package
          command: cd typescript && yarn build

      - run:
          name: Publish package
          command: cd typescript && npm publish

workflows:
  version: 2
  default:
    jobs:
      - build_ruby
      - test_ruby:
          requires:
            - build_ruby
      - build_typescript
      - test_typescript:
          requires:
            - build_typescript
  release:
    jobs:
      - deploy_ruby:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy_typescript:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
